.TH CCAT 1 "February 20, 2017" "Jean-Marc Bourguet" "Jean-Marc Bourguet's Utilities"

.SH NAME
ccat \- cat files with C syntax

.SH SYNOPSYS
.B ccat
[\|\fIOPTIONS\fR...\|] [\|\ffiles\fR...\|]

.SH DESCRIPTION
.B ccat
print the files using a C syntaxt

.SH OPTIONS

.TP
.B \-h
built in help.

.TP
.B \-l
use the current locale instead of the C one to determine valid characters.

.TP
.B \-s
print valid strings, the result can be included in a C program as a string.

.SH SEE ALSO
.BR cat (1)
